[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Revise     = "295af30f-e4ad-537b-8983-00126c2a3abe"
Semigroups = "f8a5e1c0-7b2d-4a3e-9c6f-1d2e3f4a5b6c"

[sources]
Semigroups = {path = ".."}

[compat]
Documenter = "1"
